### ISSUE TITLE
Vocab Files

### ISSUE THREAD

**Issue by DishaJindal** [hunterhector/EventSalience#1]
Hi, I am trying to reproduce the results in this paper. From where could I get the vocab files mentioned in this config file: http://accra.sp.cs.cmu.edu/~zhengzhl/downloads/event_salience/config/hash/conf_hash_event_train.
Thanks

**Comment by hunterhector** [comment]
Looks like I missed it in the README, the folder can be obtained here:

http://accra.sp.cs.cmu.edu/~zhengzhl/downloads/event_salience/vocab/

**Comment by DishaJindal** [comment]
Thank You!
